import React, { useState } from 'react';
import { 
  FileText, 
  Copy, 
  Check, 
  Download, 
  X, 
  ShieldAlert, 
  KeyRound,
  FileCode
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface ExportReportModalProps {
  data: AnalysisResult;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  data,
  onClose,
}) => {
  const [copied, setCopied] = useState<boolean>(false);
  const [reportFormat, setReportFormat] = useState<'markdown' | 'json'>('markdown');

  // Generate Markdown report
  const generateMarkdown = (): string => {
    const criticalCreds = data.cleartextItems.filter(i => i.riskLevel === 'critical');
    const highCreds = data.cleartextItems.filter(i => i.riskLevel === 'high');

    return `# PCAP Security Audit & Forensics Report
Generated: ${new Date().toUTCString()}
File: ${data.filename}
Capture Duration: ${data.stats.durationSeconds}s | Total Packets: ${data.stats.totalPackets} | Volume: ${(data.stats.totalBytes / 1024).toFixed(1)} KB

---

## 1. Executive Summary
- **Unencrypted Findings Harvested:** ${data.cleartextItems.length}
- **Critical Passwords / Tokens Exposed:** ${criticalCreds.length}
- **Security Anomalies Flagged:** ${data.anomalies.length}

${criticalCreds.length > 0 ? `> **CRITICAL WARNING:** This network capture contains cleartext passwords and authentication secrets transmitted in the clear over insecure protocols. Immediate credential revocation and protocol TLS/SSH enforcement is recommended.` : `> **NOTICE:** No critical plaintext passwords detected in this capture.`}

---

## 2. Unencrypted Data Inventory
${data.cleartextItems.length === 0 ? '_No cleartext data identified._' : `
| Category | Protocol | Label | Sensitive Value | Endpoints | Risk |
|---|---|---|---|---|---|
${data.cleartextItems.map(i => `| ${i.category} | ${i.protocol} | ${i.label} | \`${i.value}\` | \`${i.sourceIp} -> ${i.destIp}\` | **${i.riskLevel.toUpperCase()}** |`).join('\n')}
`}

---

## 3. Flagged Security Anomalies & Threats
${data.anomalies.length === 0 ? '_No security anomalies detected._' : `
${data.anomalies.map((a, idx) => `
### ${idx + 1}. [${a.severity.toUpperCase()}] ${a.title}
- **Category:** ${a.category}
- **MITRE ATT&CK:** ${a.mitreId}
- **Source:** \`${a.sourceIp}${a.sourcePort ? `:${a.sourcePort}` : ''}\` -> **Destination:** \`${a.destinationIp}${a.destinationPort ? `:${a.destinationPort}` : ''}\`
- **Protocol:** ${a.protocol}
- **Details:** ${a.description}
- **Evidence:**
${Object.entries(a.evidence).map(([k, v]) => `  - **${k}:** ${Array.isArray(v) ? v.join(', ') : String(v)}`).join('\n')}
`).join('\n')}
`}

---

## 4. Traffic & Protocol Profile
| Protocol | Packet Count | Bytes |
|---|---|---|
${Object.entries(data.stats.protocolCounts).map(([p, count]) => `| ${p} | ${count} | ${data.stats.protocolBytes[p] || 0} B |`).join('\n')}

---
*Report generated by PacketLens PCAP Forensics Engine*
`;
  };

  const markdownContent = generateMarkdown();
  const jsonContent = JSON.stringify(data, null, 2);
  const activeContent = reportFormat === 'markdown' ? markdownContent : jsonContent;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([activeContent], { 
      type: reportFormat === 'markdown' ? 'text/markdown' : 'application/json' 
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security_audit_${data.filename.replace(/\.[^/.]+$/, '')}.${reportFormat === 'markdown' ? 'md' : 'json'}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-3xl max-h-[88vh] flex flex-col shadow-2xl relative">
        
        {/* Modal Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white tracking-tight">
                Export Forensic Security Audit Report
              </h3>
              <p className="text-xs text-slate-400">
                Full technical audit summary with cleartext data and MITRE anomalies
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Selector Bar */}
        <div className="px-5 py-3 bg-slate-950/60 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setReportFormat('markdown')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5 ${
                reportFormat === 'markdown'
                  ? 'bg-amber-500 text-slate-950'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Markdown (.md)</span>
            </button>

            <button
              onClick={() => setReportFormat('json')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5 ${
                reportFormat === 'json'
                  ? 'bg-cyan-500 text-slate-950'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              <FileCode className="w-3.5 h-3.5" />
              <span>Structured JSON (.json)</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium border border-slate-700 transition-colors flex items-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-3 py-1 bg-amber-600 hover:bg-amber-500 text-white rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Content Preview */}
        <div className="p-5 flex-1 overflow-y-auto">
          <pre className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-xs font-mono text-slate-300 whitespace-pre-wrap leading-relaxed select-all">
            {activeContent}
          </pre>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/40 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-medium"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
